<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BMS.Ingestion.Business\BMS.Ingestion.Business.csproj" />
    <ProjectReference Include="..\BMS.Ingestion.Common\BMS.Ingestion.Common.csproj" />
    <ProjectReference Include="..\BMS.Ingestion.Domain\BMS.Ingestion.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.0" />
  </ItemGroup>

</Project>
