<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="2.52.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="2.1.0" OutputItemType="Analyzer" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.3.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Storage.Queues" Version="5.5.5" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.3.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SPO.Ingestion.App\SPO.Ingestion.App.csproj" />
    <ProjectReference Include="..\SPO.Ingestion.Business\SPO.Ingestion.Business.csproj" />
    <ProjectReference Include="..\SPO.Ingestion.Common\SPO.Ingestion.Common.csproj" />
    <ProjectReference Include="..\SPO.Ingestion.DataAccess\SPO.Ingestion.DataAccess.csproj" />
    <ProjectReference Include="..\SPO.Ingestion.Domain\SPO.Ingestion.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="..\config\spo-ingestion.json" Link="config\spo-ingestion.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
