<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\BMS.Fake\BMS.Fake.App\BMS.Fake.App.csproj" />
    <ProjectReference Include="..\..\BMS.Fake\BMS.Fake.Business\BMS.Fake.Business.csproj" />
    <ProjectReference Include="..\..\BMS.Fake\BMS.Fake.DataAccess\BMS.Fake.DataAccess.csproj" />
    <ProjectReference Include="..\..\BMS.Fake\BMS.Fake.Domain\BMS.Fake.Domain.csproj" />
    <ProjectReference Include="..\..\BMS.Ingestion\BMS.Ingestion.Business\BMS.Ingestion.Business.csproj" />
    <ProjectReference Include="..\..\BMS.Ingestion\BMS.Ingestion.Common\BMS.Ingestion.Common.csproj" />
    <ProjectReference Include="..\..\BMS.Ingestion\BMS.Ingestion.DataAccess\BMS.Ingestion.DataAccess.csproj" />
    <ProjectReference Include="..\..\BMS.Ingestion\BMS.Ingestion.Domain\BMS.Ingestion.Domain.csproj" />
    <ProjectReference Include="..\..\Dataverse.SyncWorker\Dataverse.SyncWorker.Business\Dataverse.SyncWorker.Business.csproj" />
    <ProjectReference Include="..\..\Dataverse.SyncWorker\Dataverse.SyncWorker.App\Dataverse.SyncWorker.App.csproj" />
    <ProjectReference Include="..\..\Dataverse.SyncWorker\Dataverse.SyncWorker.Common\Dataverse.SyncWorker.Common.csproj" />
    <ProjectReference Include="..\..\Dataverse.SyncWorker\Dataverse.SyncWorker.DataAccess\Dataverse.SyncWorker.DataAccess.csproj" />
    <ProjectReference Include="..\..\Dataverse.SyncWorker\Dataverse.SyncWorker.Domain\Dataverse.SyncWorker.Domain.csproj" />
    <ProjectReference Include="..\..\SPO.Ingestion.Business\SPO.Ingestion.Business.csproj" />
    <ProjectReference Include="..\..\SPO.Ingestion.Common\SPO.Ingestion.Common.csproj" />
    <ProjectReference Include="..\..\SPO.Ingestion.DataAccess\SPO.Ingestion.DataAccess.csproj" />
    <ProjectReference Include="..\..\SPO.Ingestion.Domain\SPO.Ingestion.Domain.csproj" />
  </ItemGroup>

</Project>
