import { makeStyles, tokens } from "@fluentui/react-components";

// Toàn bộ style của dashboard nằm trong một hook để dùng Fluent UI tokens
// và tự thích ứng theo breakpoint của trang Power Apps.
export const useStyles = makeStyles({
    root: {
        position: "relative",
        contain: "layout",
        display: "flex",
        flexDirection: "column",
        width: "100%",
        height: "100%",
        overflowY: "auto",
        boxSizing: "border-box",
        color: tokens.colorNeutralForeground1,
        backgroundColor: tokens.colorNeutralBackground2,
    },
    content: {
        display: "flex",
        flexDirection: "column",
        gap: tokens.spacingVerticalXL,
        width: "100%",
        maxWidth: "96rem",
        marginLeft: "auto",
        marginRight: "auto",
        padding: tokens.spacingHorizontalXXL,
        boxSizing: "border-box",
        "@media (max-width: 768px)": {
            padding: tokens.spacingHorizontalL,
            gap: tokens.spacingVerticalL,
        },
    },
    hero: {
        display: "flex",
        alignItems: "flex-start",
        justifyContent: "space-between",
        gap: tokens.spacingHorizontalXL,
        padding: tokens.spacingHorizontalXXL,
        borderRadius: tokens.borderRadiusXLarge,
        color: tokens.colorNeutralForegroundOnBrand,
        backgroundImage: `linear-gradient(135deg, ${tokens.colorBrandBackground}, ${tokens.colorPaletteTealForeground2})`,
        boxShadow: tokens.shadow16,
        "@media (max-width: 768px)": {
            flexDirection: "column",
            padding: tokens.spacingHorizontalXL,
        },
    },
    heroCopy: {
        display: "flex",
        flexDirection: "column",
        gap: tokens.spacingVerticalS,
        minWidth: 0,
    },
    eyebrow: {
        color: tokens.colorNeutralForegroundOnBrand,
        fontSize: tokens.fontSizeBase200,
        fontWeight: tokens.fontWeightSemibold,
        letterSpacing: "0.08em",
        textTransform: "uppercase",
    },
    title: {
        margin: 0,
        color: tokens.colorNeutralForegroundOnBrand,
        fontFamily: tokens.fontFamilyBase,
        fontSize: tokens.fontSizeHero900,
        fontWeight: tokens.fontWeightSemibold,
        lineHeight: tokens.lineHeightHero900,
        "@media (max-width: 480px)": {
            fontSize: tokens.fontSizeHero700,
            lineHeight: tokens.lineHeightHero700,
        },
    },
    heroDescription: {
        maxWidth: "52rem",
        color: tokens.colorNeutralForegroundOnBrand,
        fontSize: tokens.fontSizeBase400,
        lineHeight: tokens.lineHeightBase400,
    },
    userPanel: {
        display: "flex",
        flexDirection: "column",
        gap: tokens.spacingVerticalS,
        minWidth: "16rem",
        padding: tokens.spacingHorizontalL,
        border: `${tokens.strokeWidthThin} solid rgba(255, 255, 255, 0.38)`,
        borderRadius: tokens.borderRadiusLarge,
        backgroundColor: "rgba(0, 0, 0, 0.14)",
        "@media (max-width: 768px)": {
            width: "100%",
            minWidth: 0,
            boxSizing: "border-box",
        },
    },
    userLine: {
        display: "flex",
        alignItems: "center",
        gap: tokens.spacingHorizontalS,
        color: tokens.colorNeutralForegroundOnBrand,
    },
    profileHint: {
        color: tokens.colorNeutralForegroundOnBrand,
        fontSize: tokens.fontSizeBase200,
        lineHeight: tokens.lineHeightBase200,
    },
    section: {
        display: "flex",
        flexDirection: "column",
        gap: tokens.spacingVerticalM,
    },
    sectionHeader: {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        gap: tokens.spacingHorizontalM,
        flexWrap: "wrap",
    },
    sectionHeading: {
        display: "flex",
        flexDirection: "column",
        gap: tokens.spacingVerticalXXS,
    },
    sectionTitle: {
        margin: 0,
        fontFamily: tokens.fontFamilyBase,
        fontSize: tokens.fontSizeBase600,
        fontWeight: tokens.fontWeightSemibold,
        lineHeight: tokens.lineHeightBase600,
    },
    sectionDescription: {
        color: tokens.colorNeutralForeground2,
    },
    kpiGrid: {
        display: "grid",
        gridTemplateColumns: "repeat(auto-fit, minmax(11rem, 1fr))",
        gap: tokens.spacingHorizontalM,
    },
    kpiCard: {
        display: "flex",
        flexDirection: "column",
        gap: tokens.spacingVerticalM,
        minHeight: "8.75rem",
        padding: tokens.spacingHorizontalL,
        border: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke2}`,
        borderRadius: tokens.borderRadiusLarge,
        backgroundColor: tokens.colorNeutralBackground1,
        boxShadow: tokens.shadow2,
    },
    kpiTop: {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        gap: tokens.spacingHorizontalS,
    },
    kpiIcon: {
        display: "inline-flex",
        alignItems: "center",
        justifyContent: "center",
        width: "2rem",
        height: "2rem",
        borderRadius: tokens.borderRadiusCircular,
        color: tokens.colorBrandForeground1,
        backgroundColor: tokens.colorBrandBackground2,
    },
    kpiValue: {
        fontFamily: tokens.fontFamilyBase,
        fontSize: tokens.fontSizeHero800,
        fontWeight: tokens.fontWeightSemibold,
        lineHeight: tokens.lineHeightHero800,
        fontVariantNumeric: "tabular-nums",
    },
    kpiLabel: {
        color: tokens.colorNeutralForeground2,
        fontSize: tokens.fontSizeBase300,
    },
    countNote: {
        color: tokens.colorNeutralForeground3,
        fontSize: tokens.fontSizeBase200,
    },
    pipeline: {
        display: "grid",
        gridTemplateColumns: "repeat(4, minmax(9rem, 1fr))",
        gap: tokens.spacingHorizontalS,
        overflowX: "auto",
        paddingBottom: tokens.spacingVerticalXS,
    },
    pipelineStep: {
        position: "relative",
        display: "flex",
        alignItems: "center",
        gap: tokens.spacingHorizontalM,
        minWidth: "9rem",
        padding: tokens.spacingHorizontalL,
        borderRadius: tokens.borderRadiusLarge,
        color: tokens.colorNeutralForeground1,
        backgroundColor: tokens.colorNeutralBackground1,
        border: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke2}`,
    },
    pipelineIcon: {
        display: "inline-flex",
        alignItems: "center",
        justifyContent: "center",
        flexShrink: 0,
        width: "2.25rem",
        height: "2.25rem",
        borderRadius: tokens.borderRadiusCircular,
        color: tokens.colorBrandForeground1,
        backgroundColor: tokens.colorBrandBackground2,
    },
    pipelineCopy: {
        display: "flex",
        flexDirection: "column",
        gap: tokens.spacingVerticalXXS,
        minWidth: 0,
    },
    pipelineLabel: {
        fontWeight: tokens.fontWeightSemibold,
    },
    pipelineDetail: {
        color: tokens.colorNeutralForeground2,
        fontSize: tokens.fontSizeBase200,
    },
    pipelineArrow: {
        position: "absolute",
        right: `calc(-1 * ${tokens.spacingHorizontalS})`,
        zIndex: 1,
        color: tokens.colorNeutralForeground3,
        transform: "translateX(50%)",
    },
    actionGrid: {
        display: "grid",
        gridTemplateColumns: "repeat(auto-fit, minmax(13rem, 1fr))",
        gap: tokens.spacingHorizontalM,
    },
    actionButton: {
        justifyContent: "flex-start",
        minHeight: "2.75rem",
    },
    toolbar: {
        display: "flex",
        alignItems: "center",
        gap: tokens.spacingHorizontalS,
        flexWrap: "wrap",
    },
    search: {
        minWidth: "16rem",
        "@media (max-width: 480px)": {
            minWidth: "100%",
        },
    },
    message: {
        display: "flex",
        alignItems: "flex-start",
        gap: tokens.spacingHorizontalS,
        padding: tokens.spacingHorizontalL,
        borderRadius: tokens.borderRadiusMedium,
        color: tokens.colorStatusDangerForeground1,
        backgroundColor: tokens.colorStatusDangerBackground1,
        border: `${tokens.strokeWidthThin} solid ${tokens.colorStatusDangerBorder1}`,
    },
    loading: {
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        minHeight: "15rem",
        padding: tokens.spacingVerticalXXL,
        borderRadius: tokens.borderRadiusLarge,
        backgroundColor: tokens.colorNeutralBackground1,
    },
    empty: {
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        gap: tokens.spacingVerticalS,
        minHeight: "10rem",
        padding: tokens.spacingVerticalXXL,
        textAlign: "center",
        borderRadius: tokens.borderRadiusLarge,
        color: tokens.colorNeutralForeground2,
        backgroundColor: tokens.colorNeutralBackground1,
        border: `${tokens.strokeWidthThin} dashed ${tokens.colorNeutralStroke2}`,
    },
    dataCard: {
        overflow: "hidden",
        border: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke2}`,
        borderRadius: tokens.borderRadiusLarge,
        backgroundColor: tokens.colorNeutralBackground1,
    },
    dataCardHeader: {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        gap: tokens.spacingHorizontalM,
        padding: tokens.spacingHorizontalL,
        borderBottom: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke2}`,
    },
    dataCardTitle: {
        fontWeight: tokens.fontWeightSemibold,
    },
    gridScroller: {
        overflowX: "auto",
    },
    cellLayout: {
        minWidth: 0,
        overflow: "hidden",
    },
    truncate: {
        display: "block",
        minWidth: 0,
        overflow: "hidden",
        textOverflow: "ellipsis",
        whiteSpace: "nowrap",
    },
    numeric: {
        fontFamily: tokens.fontFamilyBase,
        fontVariantNumeric: "tabular-nums",
    },
    latestReceipt: {
        display: "grid",
        gridTemplateColumns: "repeat(4, minmax(0, 1fr))",
        gap: tokens.spacingHorizontalL,
        padding: tokens.spacingHorizontalL,
        borderTop: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke2}`,
        backgroundColor: tokens.colorNeutralBackground3,
        "@media (max-width: 768px)": {
            gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
        },
        "@media (max-width: 480px)": {
            gridTemplateColumns: "1fr",
        },
    },
    receiptField: {
        display: "flex",
        flexDirection: "column",
        gap: tokens.spacingVerticalXXS,
        minWidth: 0,
    },
    receiptLabel: {
        color: tokens.colorNeutralForeground3,
        fontSize: tokens.fontSizeBase200,
    },
});
